const currentVersion = 3;

const initialTeams = [
  {
    key: "hj",
    displayName: "הפועל ירושלים",
    initialPoints: 37,
    goalDiffrence: -1,
  },
  {
    key: "hh",
    displayName: "הפועל חדרה",
    initialPoints: 32,
    goalDiffrence: -16,
  },
  {
    key: "mpt",
    displayName: "מכבי פ״ת",
    initialPoints: 30,
    goalDiffrence: -20,
  },
  {
    key: "mn",
    displayName: "מכבי נתניה",
    initialPoints: 29,
    goalDiffrence: -15,
  },
  {
    key: "bj",
    displayName: "בית״ר ירושלים",
    initialPoints: 28,
    goalDiffrence: 2,
  },
  {
    key: "hta",
    displayName: "הפועל ת״א",
    initialPoints: 27,
    goalDiffrence: -10,
  },
  {
    key: "msa",
    displayName: "מס אשדוד",
    initialPoints: 26,
    goalDiffrence: -21,
  },
  {
    key: "hpt",
    displayName: "הפועל פ״ת",
    initialPoints: 21,
    goalDiffrence: -19,
  },
];

const resultsTypes = {
  HOME: 1,
  AWAY: 2,
  TIE: 3,
};

const completedRounds = [];

const initialFixtures = [
  //30
  {
    home: "hpt",
    away: "bj",
    round: 29,
    homeGoals: undefined,
    awayGoals: undefined,
    result: undefined,
    lock: false,
  },
  {
    home: "mn",
    away: "hj",
    round: 29,
    homeGoals: 1,
    awayGoals: 0,
    result: 1,
    lock: true,
  },
  {
    home: "hh",
    away: "msa",
    round: 29,
    homeGoals: undefined,
    awayGoals: undefined,
    result: undefined,
    lock: false,
  },
  {
    home: "mpt",
    away: "hta",
    round: 29,
    homeGoals: 4,
    awayGoals: 2,
    result: 1,
    lock: true,
  },
  {
    home: "msa",
    away: "hpt",
    round: 30,
    homeGoals: undefined,
    awayGoals: undefined,
    result: undefined,
    lock: false,
  },
  {
    home: "hj",
    away: "hh",
    round: 30,
    homeGoals: undefined,
    awayGoals: undefined,
    result: undefined,
    lock: false,
  },
  {
    home: "hta",
    away: "bj",
    round: 30,
    homeGoals: undefined,
    awayGoals: undefined,
    result: undefined,
    lock: false,
  },
  {
    home: "mpt",
    away: "mn",
    round: 30,
    homeGoals: undefined,
    awayGoals: undefined,
    result: undefined,
    lock: false,
  },
  {
    home: "hpt",
    away: "hj",
    round: 31,
    homeGoals: undefined,
    awayGoals: undefined,
    result: undefined,
    lock: false,
  },
  {
    home: "mn",
    away: "hta",
    round: 31,
    homeGoals: undefined,
    awayGoals: undefined,
    result: undefined,
    lock: false,
  },
  {
    home: "hh",
    away: "mpt",
    round: 31,
    homeGoals: undefined,
    awayGoals: undefined,
    result: undefined,
    lock: false,
  },
  {
    home: "bj",
    away: "msa",
    round: 31,
    homeGoals: undefined,
    awayGoals: undefined,
    result: undefined,
    lock: false,
  },
  {
    home: "mpt",
    away: "hpt",
    round: 32,
    homeGoals: undefined,
    awayGoals: undefined,
    result: undefined,
    lock: false,
  },
  {
    home: "hta",
    away: "msa",
    round: 32,
    homeGoals: undefined,
    awayGoals: undefined,
    result: undefined,
    lock: false,
  },
  {
    home: "mn",
    away: "hh",
    round: 32,
    homeGoals: undefined,
    awayGoals: undefined,
    result: undefined,
    lock: false,
  },
  {
    home: "hj",
    away: "bj",
    round: 32,
    homeGoals: undefined,
    awayGoals: undefined,
    result: undefined,
    lock: false,
  },
  {
    home: "hpt",
    away: "mn",
    round: 33,
    homeGoals: undefined,
    awayGoals: undefined,
    result: undefined,
    lock: false,
  },
  {
    home: "hh",
    away: "hta",
    round: 33,
    homeGoals: undefined,
    awayGoals: undefined,
    result: undefined,
    lock: false,
  },
  {
    home: "bj",
    away: "mpt",
    round: 33,
    homeGoals: undefined,
    awayGoals: undefined,
    result: undefined,
    lock: false,
  },
  {
    home: "msa",
    away: "hj",
    round: 33,
    homeGoals: undefined,
    awayGoals: undefined,
    result: undefined,
    lock: false,
  },
];

const GAMES_PLAYED_INITIAL = 28;
const BASE_POSITION = 7;

export {
  initialTeams,
  initialFixtures,
  resultsTypes,
  currentVersion,
  completedRounds,
  GAMES_PLAYED_INITIAL,
  BASE_POSITION,
};

// {
//   home: "hpt",
//   away: "kfs",
//   round: 31,
//   homeGoals: 3,
//   awayGoals: 4,
//   result: 2,
//   lock: true,
// },
